import { Document, HttpMethod, Normalized, Paths } from '@/interfaces.ts';
import Normalize from '@/Normalization.ts';
import FileSystemInteraction from './FileSystemInteraction.ts';

const tribute: string[] = [
  '/*\n',
  '** ------------------------------------------ **\n',
  '** This file was generated by @omar-labana/ez **\n',
  '** @source: https://github.com/omar-labana/ez **\n',
  '** ------------------------------------------ **\n',
  '*/\n\n',
];

class Generator {
  normalize: Normalize;
  fileSystemInteraction: FileSystemInteraction;
  map = new Map<string, Paths[]>([['miscellaneous', []]]);

  constructor() {
    this.normalize = new Normalize();
    this.fileSystemInteraction = new FileSystemInteraction();
  }

  prepare(document: Document) {
    for (const [path, pathItem] of Object.entries(document.paths)) {
      for (const operation of Object.values(pathItem)) {
        if (!operation.tags || operation.tags.length === 0) {
          this.map.get('miscellaneous')?.push({ [path]: pathItem });
        } else {
          if (this.map.has(operation.tags[0])) {
            this.map.get(operation.tags[0])?.push({ [path]: pathItem });
          } else {
            this.map.set(operation.tags[0], [{ [path]: pathItem }]);
          }
        }
      }
    }

    for (const [tag, paths] of this.map) {
      paths.sort((a, b) => Object.keys(a)[0].localeCompare(Object.keys(b)[0]));
      this.map.set(tag, paths);
    }
  }

  conserve(tag: string): Normalized {
    const nameRepository = this.normalize.nameRepository(tag);
    const normalized: Normalized = {
      repository: nameRepository,
      operations: [],
    };

    const paths = this.map.get(tag) || [];
    for (const pathObj of paths) {
      const [key, value] = Object.entries(pathObj)[0];
      for (const [operationKey, operationValue] of Object.entries(value)) {
        normalized.operations.push({
          method: operationKey as HttpMethod,
          path: key,
          summary: operationValue.summary || '',
          description: operationValue.description || '',
          function: this.normalize.nameRequest(operationKey, key),
          operationId: operationValue.operationId || '',
          payload: (operationValue.operationId || '') + 'Request',
          returns: '',
        });
      }
    }

    return normalized;
  }

  generate() {
    for (const tag of this.map.keys()) {
      const normalized = this.conserve(tag);

      // const repoFunction =
      //   `const ${normalized.repository}=()=>{// Repository logic here};export default ${normalized.repository};`;

      this.fileSystemInteraction.writeRepository(
        normalized.repository,
        tribute.join(''),
      );
    }
  }
}

export default Generator;
